name: Unit tests

on:
  push:
    branches:
      - main
    paths:
      - "src"
      - ".github/workflows/main.yml"
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "src"
      - ".github/workflows/main.yml"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: yarn
      - run: yarn test
